package clickergame;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LauncherTest {
    @Test public void testAppHasAGreeting() {
        Launcher classUnderTest = new Launcher();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
