package clickergame;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Launcher {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new Launcher().getGreeting());
    }
}
